config/routes.rb
Rails.application.routes.draw do
  
  resources :projects
  resources :courses
  # get 'welcome/index'
  root 'students#index'
  # put "/students/:id", to: "students#update_student"
  get '/update_student/:id', to: 'students#update_student', as: "update_student"
  put '/updating_student_details/:id', to: 'students#updating_student_details', as: "updating_student_details"

  get 'moso', action: :index, controller: 'students'

  resources :students

  namespace :admin do
    resources :students
  end
  
  get '/greet', to: 'students#greet'
  get 'add',  to: 'students#add'
  # scope "api/v1" do 
  #   resources :users
  # end

  # namespace :api do
  #   namespace :v1 do
  #     resources :users do
  #       get "status_update", on: :collection
  #     end
  #   end
  #   namespace :v2 do
  #     resources :users
  #   end
  # end

  resources "users" do
    resources "orders" 
  end
  
  #With namespace
  # namespace :admin do
  #   resources :articles, :comments
  # end

  #with module and scope
  # scope module: 'admin' do
  #   resources :articles, :comments
  # end

  #Nested resources
  # resources :magazines do
  #   resources :ads
  # end

  #nested under nested resources

  
  # resources :publishers do
  #   resources :magazines do
  #     resources :photos
  #   end
  # end
  #shalow routing
  # resources :articles do
  #   resources :comments, only: [:index, :new, :create]
  # end

  #member routes
  # resources :photos do
  #   member do
  #     get 'preview'
  #     put 'preview/edit'
  #   end
  # end

  #collection routes
  resources :photos do
    collection do
      get 'search'
    end
  end

  

  
end

app/models/student.rb
class Student < ApplicationRecord
    paginates_per 3
    has_many :blogs
    has_and_belongs_to_many :courses
    has_many :student_projects
    has_many :projects, through: :student_projects
    validates :first_name, :last_name, :email, presence: true

    before_create :display_greetings

    def display_greetings
        puts "Hello, You executed before action callback!", 1000+12212
    end

    def full_name
        "#{first_name} #{last_name}"
    end

    def name_with_email
        "#{first_name} #{last_name} #{email}"
    end
    

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # skip_before_actrion :require_me, only: [:new, :create]

  def index 
    @q = Student.ransack(params[:q])
    @students = @q.result(distinct: true).page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @students }
      format.json { render json: @students }
    end
  end

  def new 
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path,notice: "Student Created successfully"
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id]) 
    if @student.update(student_params)
      redirect_to student_path(@student), notice: 'Student Updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.delete
    redirect_to students_path,notice: 'Student Deleted successfully'
  end

  def update_student
 
    @student = Student.find(params[:id])
  end

  def updating_student_details

    @student = Student.find(params[:id]) 
    @student.update(first_name: params[:student][:first_name])
    redirect_to student_path(@student)
  end


  def greet
    @message = "Hello, World!"
  end

  def add 
    @add = 1000+2000
  end

  private

  def student_params
    params.require(:student).permit(:first_name,:last_name,:email)
  end

  def require_me
    puts "required"
  end
end

app/helpers/students_helper.rb
module StudentsHelper
    def add
        a=100
        b=200
        return "Addition of value #{a+b}"
    end
end

app/views/students/_form.html.erb
<%= form_with model: student do |form|%>
   <%if @student.errors.any?%>
     <%@student.errors.full_messages.each do |message|%>
        <p><%= message%></p>
     <%end%>
    <%end%>
    <div class = "form-group">
        <%= form.label :first_name%>
        <%= form.text_field :first_name, class: "form-control form-control-lg"%>
    </div>

    <div class = "form-group">
        <%= form.label :last_name%>
        <%= form.text_field :last_name,  class: "form-control form-control-lg"%>
    </div>

    <div class = "form-group">
        <%= form.label :Email%>
        <%= form.email_field :email , class: "form-control form-control-lg"%>
    </div>
   
    <div class = "form-group">
    <br>
    <center><%= form.submit %></center>
    </div>
    <br> 

<%end%>

app/views/students/add.html.erb
<h1>Addition value </h1>

<%= @add %>

<h1>Test Active support</h1>
<%= "hello".from(1) %><br>
<%= "foo".starts_with?("f") %>

<h1>plurize</h1>
<%= "work".pluralize%>

<h1>Dashrize</h1>
<%="monesh_soni".dasherize%>

<h1>Tablize</h1>
<%= "Invoice".tableize %>
<h1>Capitilize</h1>
<%= "monesh".humanize  %>

<h1>Foreign key</h1>
<%= "User".foreign_key%>
<h1>Date</h1>
<%= "2010-07-27".to_datetime %>
<h1>Time</h1>
<%= 1.day.from_now %>

<h1>Phone</h1>
<%# <%= 5551234.to_fs(:phone)%> %>
<h1>Titalize</h1>
<%= "alice in wonderland".titleize%>

<h1>Week</h1>
<%= 2.weeks.from_now%>
<h1>Ordinize</h1>

<%= 2.ordinalize%>

<h1>Month</h1>
<%=(4.months + 5.years).from_now%>

<h1>Decimal</h1>
<%= BigDecimal(5.00, 6).to_s   %>
<h1>Including</h1>
<%= [ 1, 2, 3 ].including(4, 5)   %>
<h1>Excluding</h1>
<%= ["David", "Rafael", "Aaron", "Todd"].excluding("Aaron", "Todd")%>

<h1>Pluck</h1>
<%= [{ name: "monesh" }, { name: "sanjay    " }, { name: "Aaron" }].pluck(:name)%>

<h1>Sentence</h1>
<%= %w(Monesh is the RoR Coder).to_sentence %>

<h1>Group</h1>
<%= [1, 2, 3].in_groups_of(1, false) %>
<br>
<%= %w(1 2 3 4 5 6 7).in_groups(1)%>
<br>

<%= %w(1 2 3 4 5 6 7).in_groups(3, "0")%>

<h1>Split</h1>
<%= (1..5).to_a.split("monesh")%>

<h1>Today and tommorow</h1>
<%=(Date.today..Date.tomorrow).to_s%>
<h1>Week</h1>
<%date = Date.new(2010, 6, 7) %>
<%=date.years_ago(10)%>

<h1>Start Date & End Date</h1>
<%date = Date.new(2010, 6, 7)%>
<%=date.end_of_day%>

<h1>Time Zone</h1>
<%now = DateTime.current%>
<%= now.gmtime()%>
<%= Time.now.to_date%>

app/views/students/edit.html.erb
<h1>Edit Student</h1>
<%= render "form", student: @student%>
<%= link_to 'Back', students_path%>

app/views/students/greet.html.erb
<h1>Greeting</h1>
<p><%= @message %></p>

app/views/students/index.html.erb
<div class = "col-lg-10">

<strong><h1><%= notice%></h1></strong>
<h1>Listing students</h1>
<%= search_form_for @q, url: :students do |form| %>
    <div class= "form-group">
      <%= form.label :first_name%>
      <%= form.text_field :first_name_cont ,class: "form-control"%>
    </div>

    <div class= "form-group"><br>
      <%= form.submit class: "btn btn-primary btn-lg"%>
    </div>
<% end %>
<%= link_to "Add Student", new_student_path%><br>
<br>
<table class="table table-bordered">
    <thead>
        <tr>
            
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email </th>
            <th>Add </th>
            <th colspan = "5">Actions</th>
           
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student|%>
            <tr>
                <td><%= student.name_with_email%></td>
                
                <td> <%= student.last_name%></td>
                <td> <%= add() %>  </td>
                <td> <%= student.email%></td>  

                <td><%= link_to 'View',student%></td>
                <td><%= link_to 'Edit',edit_student_path(student)%></td>
                 <td><%#= link_to "Delete", student_path(student), method: :delete %></td>
               <%#= button_to 'Delete',url_for(action: :destroy, id: student.id), data: {confirm: "Are you sure?"} %></td>
                <td><%= link_to 'Delete', student, method: :delete,
  data: {confirm: 'Are you sure you want Delete?'} %></td>
            </tr>
        <%end%>
    </tbody>
</table>

<%= paginate @students %>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>


<br>

<%#= render 'form', student: @student %>

<%
=begin %>
<%= number_to_human(1234)<br>
<%= number_to_human_size(1234)%>

<%= number_to_percentage(90, precision: 2) %><br>
<%= number_to_phone(12345678)%><br>
<%= number_with_delimiter(12345678)%><br>
<%= number_with_precision(111.2345) %> 
<%
=end %>

app/views/students/show.html.erb
<div class = "col-lg-10">
<div class="card rounded-0 shadow mt-5 mb-6">
  <div class = "card-body">
    <strong><h1><%= notice%></h1></strong>
    <h1>Student Details</h1>

    <p><strong>Name: </strong><%= @student.full_name%></p>
    <p><strong>Email: </strong><%= @student.email%></p>

    <%= link_to 'Back', students_path , class: "btn" %> 
    <%= link_to 'update student', update_student_path(@student) , class: "btn btn-secondary"%>
  </div>
</div>
</div>

app/views/students/update_student.html.erb
<%= form_with model: @student, url: updating_student_details_path, method: :put  do |form|%>
    <%if @student.errors.any?%>
        <%@student.errors.full_messages.each do |message|%>
            <p><%= message%></p>
        <%end%>
    <%end%>
    <div>
        <%= form.label :first_name%><br>
        <%= form.text_field :first_name%>
    </div>

    <div>
        <%= form.label :last_name%><br>
        <%= form.text_field :last_name%>
    </div>

    <div>
        <%= form.label :Email%><br>
        <%= form.email_field :email%>
    </div>
   
    <div>
    <%= form.submit %>
    </div>
    <br> 

<%end%>

<%= link_to 'Back', students_path %>